[package]
name = "mycurl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.9"
lazy_static = "1.5.0"
aws-lc-sys = "0.20.1"
webpki-roots = "0.26.3"
rustls = "0.23.12"
openssl = { version = "0.10", features = ["vendored"] }
httparse = "1.9.4"